/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cxro_common_device_PIXISCAM_SensorSize */

#ifndef _Included_cxro_common_device_PIXISCAM_SensorSize
#define _Included_cxro_common_device_PIXISCAM_SensorSize
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
